export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';

export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
export const MOVIES_FETCH_SUCCEEDED = 'MOVIES_FETCH_SUCCEEDED';
export const MOVIES_FETCH_FAILED = 'MOVIES_FETCH_FAILED';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const USER_DATA = 'USER_DATA';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_SEARCH = 'SHOW_SEARCH';
export const HIDE_SEARCH = 'HIDE_SEARCH';
